import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { initDatabase } from "./src/database/connection.js";
import establishmentsRouter from "./src/modules/establecimientos/establecimientos.routes.js";
import servicesRouter from "./src/modules/servicios/servicios.routes.js";
import registrosRouter from "./src/modules/registros/registros.routes.js";
import metricasRouter from "./src/modules/metricas/metricas.routes.js";
import informesRouter from "./src/modules/informes/informes.routes.js";
import alertasRouter from "./src/modules/alertas/alertas.routes.js";
import ocrRouter from "./src/modules/ocr/ocr.routes.js";
import ocrCamposRouter from "./src/modules/ocr/ocr.campos.routes.js";
import ocrPlantillasRouter from "./src/modules/ocr/ocr.plantillas.routes.js";
import parametrosRouter from "./src/modules/parametros/parametros.routes.js";
import historialRouter from "./src/modules/historial/historial.routes.js";
import configuracionRouter from "./src/modules/configuracion/configuracion.routes.js";
import detalleBoletaRouter from "./src/modules/detalleBoleta/detalle.boleta.routes.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
initDatabase();
app.use(express.json({ limit: "2mb" }));
app.use("/api/establecimientos", establishmentsRouter);
app.use("/api/servicios", servicesRouter);
app.use("/api/registros", registrosRouter);
app.use("/api/metricas", metricasRouter);
app.use("/api/informes", informesRouter);
app.use("/api/alertas", alertasRouter);
app.use("/api/ocr", ocrRouter);
app.use("/api/ocr/campos", ocrCamposRouter);
app.use("/api/ocr/plantillas", ocrPlantillasRouter);
app.use("/api/parametros", parametrosRouter);
app.use("/api/historial", historialRouter);
app.use("/api/configuracion", configuracionRouter);
app.use("/api/detalle-boleta", detalleBoletaRouter);
app.use(express.static(path.join(__dirname, "public")));
app.get("/api/health", (_req, res) => res.json({ ok: true }));
const port = Number(process.env.PORT || 3000);
if (process.env.NODE_ENV !== 'test') {
  app.listen(port, "0.0.0.0", () => console.log(`Control de consumos: http://localhost:${port}`));
}
export default app;